services:
  compleasy:
    build: .
    container_name: compleasy
    volumes:
      - ./src:/app
    environment:
      - SECRET_KEY=KQ7sk-2G0RUQ_tAAchzsGBwhxr0FpB8RzuRr5J08VQ9TUdzPAX9yOIbBC19_tiJgokQ
      - COMPLEASY_URL=https://localhost:3000
      - COMPLEASY_ADMIN_USERNAME=admin
      - COMPLEASY_ADMIN_PASSWORD=compleasy
    ports:
      - 8000:8000
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 3000:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/generate-certs.sh:/docker-entrypoint.d/40-generate-cert.sh
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - compleasy